### Задание 1
#### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [23]:
first_ = 10
last_ = 0
a = np.arange(first_-1, last_-1, -1)
print(a)

[9 8 7 6 5 4 3 2 1 0]


Еще можно так

In [24]:
a = np.arange(first_)

In [25]:
a = a[::-1]

In [26]:
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
#### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [27]:
b = np.diag(a)
print(b, "Сумма диагонали = ", np.sum(b))

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]] Сумма диагонали =  45


### Задание 3
#### Решите систему уравнений:
#### 4x + 2y + z = 4
#### x + 3y = 12
#### 5y + 4z = -3



In [28]:
from numpy import linalg

In [29]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 0, 4] ] )
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([-1.56,  4.52,  1.2 ])

In [30]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True